### ISSUE TITLE
令人兴奋的功能！服务已部署，请问hexo butterfly应该如何配置

### ISSUE THREAD

**Issue by kanbang** [twikoojs/twikoo-docker#2]
期待已久的功能，太令人兴奋了！
未使用Docker，windows下Node服务已部署，显示“云函数运行正常”
请问hexo butterfly前端应该如何配置
期待回复！谢谢先！！

**Comment by imaegoo** [comment]
还有一些影响使用的 bug 没修复，暂不建议上生产。

**Comment by imaegoo** [comment]
和 Vercel 一样的配置，主题配置中 envId 修改为部署好的环境地址即可。例如 `http://twikoo.xxx.com`

**Comment by kanbang** [comment]
谢谢，迫不及待了，吃螃蟹先
